liip_imagine:
    driver: "gd"
    filter_sets:
        cache: ~
        avatar_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120,120], mode: inset }

        recipe_thumbnail:
            quality: 85
            filters:
                thumbnail: { size: [600, 400], mode: inset }        
