vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user:
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
